from __future__ import annotations

from typing import Protocol

from .models import Agent, AuditEntry, Claim, Entity, Memory, Notification, ReviewTask, StandingQuery, Subscription


class Repository(Protocol):
    def save_agent(self, agent: Agent) -> Agent: ...
    def get_agent(self, agent_id: str) -> Agent | None: ...
    def find_agent_by_key(self, api_key: str) -> Agent | None: ...
    def list_agents(self) -> list[Agent]: ...

    def save_memory(self, memory: Memory) -> Memory: ...
    def get_memory(self, memory_id: str) -> Memory | None: ...

    def upsert_entity(self, entity: Entity) -> Entity: ...
    def get_entity(self, entity_id: str) -> Entity | None: ...
    def find_entity_by_alias(self, alias_key: str) -> Entity | None: ...

    def save_claim(self, claim: Claim) -> Claim: ...
    def update_claim(self, claim: Claim) -> Claim: ...
    def get_claim(self, claim_id: str) -> Claim | None: ...
    def list_claims(self) -> list[Claim]: ...

    def save_query(self, query: StandingQuery) -> StandingQuery: ...
    def get_query(self, query_id: str) -> StandingQuery | None: ...
    def list_queries(self) -> list[StandingQuery]: ...
    def list_queries_for_agent(self, agent_id: str) -> list[StandingQuery]: ...

    def save_notification(self, notification: Notification) -> Notification: ...
    def get_notification(self, notification_id: str) -> Notification | None: ...
    def list_notifications_for_agent(self, agent_id: str) -> list[Notification]: ...
    def mark_notification_delivered(self, notification_id: str) -> Notification | None: ...

    def save_review_task(self, review: ReviewTask) -> ReviewTask: ...
    def update_review_task(self, review: ReviewTask) -> ReviewTask: ...
    def get_review_task(self, task_id: str) -> ReviewTask | None: ...
    def list_review_tasks(self) -> list[ReviewTask]: ...

    def save_audit_entry(self, entry: AuditEntry) -> AuditEntry: ...
    def list_audit_entries(self) -> list[AuditEntry]: ...

    def save_subscription(self, subscription: Subscription) -> Subscription: ...
    def get_subscription(self, subscription_id: str) -> Subscription | None: ...
    def get_subscriptions_by_follower(self, agent_id: str) -> list[Subscription]: ...
    def get_followers_of_agent(self, agent_id: str) -> list[Subscription]: ...
    def delete_subscription(self, subscription_id: str) -> None: ...

    def snapshot(self) -> dict[str, int]: ...
    def close(self) -> None: ...
