from __future__ import annotations

from typing import Protocol

from .models import (
    Agent,
    AuditEntry,
    Claim,
    ClaimSearchResult,
    ContextPack,
    Entity,
    Memory,
    Notification,
    ReviewTask,
    SentinelVerdict,
    StandingQuery,
    Subscription,
)


class Repository(Protocol):
    def save_agent(self, agent: Agent) -> Agent: ...
    def get_agent(self, agent_id: str) -> Agent | None: ...
    def find_agent_by_key(self, api_key: str) -> Agent | None: ...
    def list_agents(self) -> list[Agent]: ...

    def save_memory(self, memory: Memory) -> Memory: ...
    def update_memory(self, memory: Memory) -> Memory: ...
    def get_memory(self, memory_id: str) -> Memory | None: ...

    def upsert_entity(self, entity: Entity) -> Entity: ...
    def get_entity(self, entity_id: str) -> Entity | None: ...
    def find_entity_by_alias(self, alias_key: str) -> Entity | None: ...

    def save_claim(self, claim: Claim) -> Claim: ...
    def update_claim(self, claim: Claim) -> Claim: ...
    def get_claim(self, claim_id: str) -> Claim | None: ...
    def list_claims(self) -> list[Claim]: ...
    def list_claims_for_memory(self, memory_id: str) -> list[Claim]: ...
    def search_claims(
        self,
        query: str,
        limit: int = 100,
        requester_agent_id: str | None = None,
        requester_org_id: str | None = None,
        exclude_priced_cross_org: bool = False,
    ) -> list[ClaimSearchResult]: ...

    def save_query(self, query: StandingQuery) -> StandingQuery: ...
    def get_query(self, query_id: str) -> StandingQuery | None: ...
    def list_queries(self) -> list[StandingQuery]: ...
    def list_queries_for_agent(self, agent_id: str) -> list[StandingQuery]: ...

    def save_notification(self, notification: Notification) -> Notification: ...
    def get_notification(self, notification_id: str) -> Notification | None: ...
    def list_notifications_for_agent(self, agent_id: str) -> list[Notification]: ...
    def mark_notification_delivered(self, notification_id: str) -> Notification | None: ...

    def save_review_task(self, review: ReviewTask) -> ReviewTask: ...
    def update_review_task(self, review: ReviewTask) -> ReviewTask: ...
    def get_review_task(self, task_id: str) -> ReviewTask | None: ...
    def list_review_tasks(self) -> list[ReviewTask]: ...

    def save_audit_entry(self, entry: AuditEntry) -> AuditEntry: ...
    def list_audit_entries(self) -> list[AuditEntry]: ...

    def save_sentinel_verdict(self, verdict: SentinelVerdict) -> SentinelVerdict: ...
    def list_verdicts_for_claim(self, claim_id: str) -> list[SentinelVerdict]: ...
    def list_verdicts(self, limit: int = 100, decision: str | None = None) -> list[SentinelVerdict]: ...

    def save_subscription(self, subscription: Subscription) -> Subscription: ...
    def get_subscription(self, subscription_id: str) -> Subscription | None: ...
    def get_subscriptions_by_follower(self, agent_id: str) -> list[Subscription]: ...
    def get_followers_of_agent(self, agent_id: str) -> list[Subscription]: ...
    def delete_subscription(self, subscription_id: str) -> None: ...

    def save_context_pack(self, pack: ContextPack) -> ContextPack: ...
    def get_context_pack(self, pack_id: str) -> ContextPack | None: ...

    def snapshot(self) -> dict[str, int]: ...
    def close(self) -> None: ...
